### ISSUE TITLE
MultiSelect label should not provide any formatting

### ISSUE THREAD

**Issue by danbopes** [bmartel/chakra-multiselect#13]
I provided a list of options:

```
[{label: 'ONE', id: 'one'}, {label: 'TWO', id: 'two'}, {label: 'THREE', id: 'three'}]
```

It provided me with a dropdown of:
One
Two
Three

Expected output:
ONE
TWO
THREE

**Comment by DOROMOLLL** [comment]
Same here, seems like the label field is ignored.

**Comment by waqaarali** [comment]
Same for me,

I did:

```js
[
   {
      label: 'test',
      value: '1'
   }
]
```

But I get `1` in return, not `test`.

**Comment by JohnnyTheTank** [comment]
Same behaviour for me, but even in the example: https://ih4jxu-3000.csb.app/

<img width="406" alt="image" src="https://github.com/bmartel/chakra-multiselect/assets/6803264/f80e1ac7-e108-4b51-9a8a-617db24532bd">

**Comment by JohnnyTheTank** [comment]
I think this line causing this behaviour: https://github.com/bmartel/chakra-multiselect/blob/main/src/MultiSelect.tsx#L282

**Comment by JohnnyTheTank** [comment]
@bmartel what do you think?
