### ISSUE TITLE
ReferenceError: crypto is not defined

### ISSUE THREAD

**Issue by ivosabev** [bmartel/chakra-multiselect#14]
I am using the component in a Remix app, which renders the components both on the server and client. Due to https://github.com/bmartel/chakra-multiselect/blob/main/src/use-select.ts#L1164 it breaks on Node and needs to be polyfilled.

I fixed it by polyfilling it in Node:
```
global.crypto = require('crypto').webcrypto;
```

Maybe avoid using Crypto, polyfill it yourself or add a warning in the README for people in the future.

**Comment by bmartel** [comment]
Hey @ivosabev, that is a good find. I don't actively develop SSR apps with Remix, but never noticed this on NextJS 🤔. Either way, easy fix. I can probably just use a more rudimentary way of producing these ids. They aren't required to be secure by any means, simply a way to produce a unique enough id for elements (a replacement for Reacts useId which requires React 18 to use).
