### ISSUE TITLE
Disable input and avoid field expansion 

### ISSUE THREAD

**Issue by francestu96** [bmartel/chakra-multiselect#27]
Hi bmartel, thank you for this amazing add to the missing Chakra UI component.
However I was wandering if there is a way to disable the input in order to avoid user to write as in normal select components. I tried by adding the **disabled** option but it doesn't work.

Moreover I'd like to avoid the expansion of the field when too many fields are selected. Maybe by replacing with the text **x selected**.

Is it possibile to achieve these results?

Thank you

**Comment by cschoreisz-pillar** [comment]
Hey there I'm encountering the same issue here !

**Comment by bmartel** [comment]
Sorry for the late reply, fixed by #35.
