### ISSUE TITLE
Pass menu props

### ISSUE THREAD

**Issue by ramiel** [bmartel/chakra-multiselect#3]
Hello. I'm trying to use this library and I have the following questions:

- the component basically accepts the Menu props, but then they're not use anywhere. e.g. 

```jsx
<MultiSelect
  options={options}
  value={value}
  onChange={onChange}
  boundary="scrollParent"
  closeOnSelect
  strategy="fixed"
/>
```

the last three options are ignored, but I expect them to be used in the list.

- Is it possible to render the list in a Portal?
- The chosen options are shown by value, but I think they should be shown by label. Is this possible?

Thanks

**Comment by bmartel** [comment]
Closing this as the intended use of customization is to use the underlying hooks and assemble an more specific API if needed at the external facing component. The intention wasn't to model the menu props, or make this operate like a menu. As for rendering in a portal, that again would be something interesting but wasn't intended to include this directly in the lib. Chosen options are shown by label with #13 being closed.
