### ISSUE TITLE
Is it possible to provide a custom filter condition when typing text in an input field?

### ISSUE THREAD

**Issue by jurilents** [bmartel/chakra-multiselect#31]
I found that when I manually type text into an input field, it automatically filters and shows options that match my input. But it's probably using the text from the "value" rather than the "label" that the user sees, and that's confusing.

Is there some way I can specify my own filter condition, or is there some other way to show that the items match the label but not the value?

```jsx
const languageOptions = [
    {value: "en-US", label: "English (United States)"}
    // 150+ items
];

// ...

 <MultiSelect
    onChange={handleLanguageChange}
    value={language}
    options={languageOptions}
    single={true}
/>
```

**Comment by mariomurrent-softwaresolutions** [comment]
This would be nice, because currently its only searching values, right? And this is not good, if the values are IDs

**Comment by bmartel** [comment]
Hey there 👋. This is a great idea, and I completely agree. I don't have the capacity to completely stay up to date with feature requests and bug fixes (as can be seen by this late reply, which I apologize 🙏). I will look to implement this as soon as I can, but if you feel up to taking a crack at it, pull requests are always welcome 👍.

**Comment by bmartel** [comment]
Realized I had already implemented this, so I added a test to outline the API and usage here: https://github.com/bmartel/chakra-multiselect/pull/38/files#diff-fb09fadbe05454dfcaa3da0f017e4de8dcbb4e35536122c3c11d95a5c613fdb7R396
