### ISSUE TITLE
yarn add chakra-multiselect throws an error

### ISSUE THREAD

**Issue by emiltsokov** [bmartel/chakra-multiselect#4]
error An unexpected error occurred: "expected hoisted manifest for \"chakra-multiselect#@chakra-ui/react#@chakra-ui/alert#@chakra-ui/icon\"".
node v14.18.1

**Comment by AryaanSheth** [comment]
I also got this error, i had to update my react version for it to work. Try running 
`yarn add react@latest react-dom@latest` or `npm install react@latest react-dom@latest`.

**Comment by bmartel** [comment]
Closing as there is no reproduction that I have been able to see this. Reopen if this persists, with a minimal reproduction case that I can debug please and thanks.
